package ecdh

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"errors"
	"fmt"
	"io"

	"golang.org/x/crypto/curve25519"
)

const (
	// KeyLen is the length of a key generated by this package, be it
	// public or private.
	KeyLen = 32
)

var (
	ErrDataLen = errors.New("data length zero or not a multiple of the blocksize")
)

// From https://cr.yp.to/ecdh.html.
func clamp(key []byte) {
	key[0] &= 248
	key[31] &= 127
	key[31] |= 64
}

// GenerateKey generates a new private key from the provided source of
// random bytes. If randsource is nil, crypto/rand.Reader is used.
func GenerateKey(randsource io.Reader) (priv []byte, err error) {
	if randsource == nil {
		randsource = rand.Reader
	}

	priv = make([]byte, KeyLen)
	_, err = io.ReadFull(randsource, priv)
	if err != nil {
		return nil, fmt.Errorf("generate private key: %w", err)
	}
	clamp(priv)

	return priv, nil
}

// GetPublic calculates a public key from a given private key.
func GetPublic(priv []byte) ([]byte, error) {
	return curve25519.X25519(priv, curve25519.Basepoint)
}

// Decrypt decrypts data using an AES key generated via ECDH from the
// provided public and private Ed25519 keys. It appends the result to
// out and returns the resulting slice.
func Decrypt(out, data, priv, pub []byte) ([]byte, error) {
	if len(data) == 0 || len(data)%aes.BlockSize != 0 {
		return nil, ErrDataLen
	}

	key, err := curve25519.X25519(priv, pub)
	if err != nil {
		return nil, fmt.Errorf("calculate key: %w", err)
	}

	c, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("create cipher: %w", err)
	}
	d := cipher.NewCBCDecrypter(c, data[:aes.BlockSize])

	data = data[aes.BlockSize:]

	start := len(out)
	out = append(out, data...)
	d.CryptBlocks(out[start:], data)

	return out, nil
}

// Encrypt encrypts data using an AES key generated via ECDH from the
// provided public and private Ed25519 keys. It appends the result to
// out and returns the resulting slice.
func Encrypt(out, data, priv, pub []byte) ([]byte, error) {
	key, err := curve25519.X25519(priv, pub)
	if err != nil {
		return nil, fmt.Errorf("calculate key: %w", err)
	}

	pad := len(data) % aes.BlockSize
	start := len(out)
	out = append(out, make([]byte, aes.BlockSize+len(data)+pad)...)
	_, err = io.ReadFull(rand.Reader, out[start:aes.BlockSize])
	if err != nil {
		return nil, fmt.Errorf("generate IV: %w", err)
	}

	c, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("create cipher: %w", err)
	}
	d := cipher.NewCBCEncrypter(c, out[start:aes.BlockSize])

	if pad != 0 {
		_, err := io.ReadFull(rand.Reader, data[len(data)-pad:])
		if err != nil {
			return nil, fmt.Errorf("generate padding: %w", err)
		}
	}

	d.CryptBlocks(out[start+aes.BlockSize:], data)

	return out, nil
}
